declare class LevelDBOptions {
  // -------------------
  // Parameters that affect behavior

  // Comparator used to define the order of keys in the table.
  // Default: a comparator that uses lexicographic byte-wise ordering
  //
  // REQUIRES: The client must ensure that the comparator supplied
  // here has the same name and orders keys *exactly* the same as the
  // comparator provided to previous open calls on the same DB.
  //const Comparator* comparator;

  /**
   * If true, the database will be created if it is missing.
   * 
   * Default: false
   */
  createIfMissing: boolean;

  /**
   * If true, an error is raised if the database already exists.
   *
   * Default: false
   */
  errorIfExists: boolean;

  // If true, the implementation will do aggressive checking of the
  // data it is processing and will stop early if it detects any
  // errors.  This may have unforeseen ramifications: for example, a
  // corruption of one DB entry may cause a large number of entries to
  // become unreadable or for the entire DB to become unopenable.
  // Default: false
  paranoidChecks: boolean;

  // Use the specified object to interact with the environment,
  // e.g. to read/write files, schedule background work, etc.
  // Default: Env::Default()
  //Env* env;

  // Any internal progress/error information generated by the db will
  // be written to info_log if it is non-NULL, or to a file stored
  // in the same directory as the DB contents if info_log is NULL.
  // Default: NULL
  //Logger* info_log;

  // -------------------
  // Parameters that affect performance

  /**
   * Amount of data to build up in memory (backed by an unsorted log
   * on disk) before converting to a sorted on-disk file.
   *
   * Larger values increase performance, especially during bulk loads.
   * Up to two write buffers may be held in memory at the same time,
   * so you may wish to adjust this parameter to control memory usage.
   * Also, a larger write buffer will result in a longer recovery time
   * the next time the database is opened.
   *
   * Default: 4MB
   */
  writeBufferSize: number;

  /**
   * Number of open files that can be used by the DB.  You may need to
   * increase this if your database has a large working set (budget
   * one open file per 2MB of working set).
   *
   * Default: 1000
   */
  maxOpenFiles: number;

  // Control over blocks (user data is stored in a set of blocks, and
  // a block is the unit of reading from disk).

  // If non-NULL, use the specified cache for blocks.
  // If NULL, leveldb will automatically create and use an 8MB internal cache.
  // Default: NULL
  //Cache* block_cache;

  /**
   * Approximate size of user data packed per block.  Note that the
   * block size specified here corresponds to uncompressed data.  The
   * actual size of the unit read from disk may be smaller if
   * compression is enabled.  This parameter can be changed dynamically.
   *
   * Default: 4K
   */
  blockSize: number;

  /**
   * Number of keys between restart points for delta encoding of keys.
   * This parameter can be changed dynamically.  Most clients should
   * leave this parameter alone.
   *
   * Default: 16
   */
  blockRestartInteval: number;

  // Leveldb will write up to this amount of bytes to a file before
  // switching to a new one.
  // Most clients should leave this parameter alone.  However if your
  // filesystem is more efficient with larger files, you could
  // consider increasing the value.  The downside will be longer
  // compactions and hence longer latency/performance hiccups.
  // Another reason to increase this parameter might be when you are
  // initially populating a large database.
  //
  // Default: 2MB
  //maxFileSize: number;

  // Compress blocks using the specified compression algorithm.  This
  // parameter can be changed dynamically.
  //
  // Default: kSnappyCompression, which gives lightweight but fast
  // compression.
  //
  // Typical speeds of kSnappyCompression on an Intel(R) Core(TM)2 2.4GHz:
  //    ~200-500MB/s compression
  //    ~400-800MB/s decompression
  // Note that these speeds are significantly faster than most
  // persistent storage speeds, and therefore it is typically never
  // worth switching to kNoCompression.  Even if the input data is
  // incompressible, the kSnappyCompression implementation will
  // efficiently detect that and will switch to uncompressed mode.
  //Compressor* compressors[256];

  // EXPERIMENTAL: If true, append to existing MANIFEST and log files
  // when a database is opened.  This can significantly speed up open.
  //
  // Default: currently false, but may become true later.
  //reuseLogs: boolean;

  // If non-NULL, use the specified filter policy to reduce disk reads.
  // Many applications will benefit from passing the result of
  // NewBloomFilterPolicy() here.
  //
  // Default: NULL
  //const FilterPolicy* filter_policy;
}

declare class LevelDBReadOptions {
  /**
   * If true, all data read from underlying storage will be
   * verified against corresponding checksums.
   * Default: false
   */
  verifyChecksums: boolean;

  /**
   * Should the data read for this iteration be cached in memory?
   * Callers may wish to set this field to false for bulk scans.
   * Default: true
   */
  fillCache: boolean;

  // If "snapshot" is non-NULL, read as of the supplied snapshot
  // (which must belong to the DB that is being read and which must
  // not have been released).  If "snapshot" is NULL, use an implicit
  // snapshot of the state at the beginning of this read operation.
  // Default: NULL
  //const Snapshot* snapshot;
}

declare class LevelDBWriteOptions {
  /**
   * If true, the write will be flushed from the operating system
   * buffer cache (by calling WritableFile::Sync()) before the write
   * is considered complete.  If this flag is true, writes will be
   * slower.
   *
   * If this flag is false, and the machine crashes, some recent
   * writes may be lost.  Note that if it is just the process that
   * crashes (i.e., the machine does not reboot), no writes will be
   * lost even if sync==false.
   *
   * In other words, a DB write with sync==false has similar
   * crash semantics as the "write()" system call.  A DB write
   * with sync==true has similar crash semantics to a "write()"
   * system call followed by "fsync()".
   *
   * Default: false
  */
  sync: boolean;
}

declare export class LevelDB {
  static COMPRESSIONS: {
    NONE: 0,
    ZLIB: 2,
    ZLIB_RAW: 4
  };

  /**
   * Initialize WebAssembly runtime. LevelDB functions must be called only
   * before this function.
   */
  static async initialize(): Promise<true>;

  /**
   * Destroy the contents of the specified database.
   * 
   * Be very careful using this method.
   * 
   * @param path 
   * @param options 
   */
  static destroy(path: string, options?: LevelDBOptions): void;

  /**
   * If a DB cannot be opened, you may attempt to call this method to
   * resurrect as much of the contents of the database as possible.
   * 
   * Some data may be lost, so be careful when calling this function
   * on a database that contains important information.
   * 
   * @param path 
   * @param options 
   */
  static repair(path: string, options?: LevelDBOptions): void;

  /**
   * Creates a LevelDB.
   * 
   * @param path - The path to the database. Use `process.cwd()` as default
   *   parent directory.
   * @param options - Options.
   */
  constructor(path: string, options?: LevelDBOptions);

  /**
   * Open the database. Throws an Error on error.
   */
  open(): boolean;

  /**
   * Close the database.
   */
  close(): void;

  /**
   * Set the database entry for "key" to "value".  Returns true on success,
   * and throws an Error on error.
   * 
   * NOTE: consider setting options.sync = true.
   * 
   * @param key 
   * @param value 
   * @param options 
   */
  put(key: Uint8Array | string, value: Uint8Array | string, options?: LevelDBWriteOptions): boolean;

  /**
   * Remove the database entry (if any) for "key".  Returns true on
   * success, and throws an Error on error.
   * 
   * It is not an error if "key" did not exist in the database.
   * 
   * NOTE: consider setting options.sync = true.
   * 
   * @param key 
   * @param options 
   */
  delete(key: Uint8Array | string, options?: LevelDBWriteOptions): boolean;

  /**
   * If the database contains an entry for "key", return the value.
   *
   * If there is no entry for "key", return undefined.
   *
   * May throws an Error on error.
   */
  get(key: Uint8Array | string, options: LevelDBReadOptions): Uint8Array | undefined;
}
